/**
 * What the phone is doing while it starts.
 *
 * Bringing this board up takes several seconds - the modem alone accounts for
 * most of it - and until now the panel showed one static word for the whole
 * wait, which is indistinguishable from a phone that has hung. This fills a
 * grid of system icons in as each one comes up, and names the one being waited
 * on underneath.
 *
 * It is drawn straight onto the panel with GxEPD2. LVGL does not exist yet at
 * this point in startup, which is also why the icons are plain packed bitmaps
 * generated by tools/gen_boot_icons.py rather than the LVGL assets the rest of
 * the UI uses.
 *
 * The cost of all this is e-paper refreshes, and they are not cheap: a partial
 * update of the whole panel is a few hundred milliseconds. Painting after every
 * one of twelve systems would add seconds to a boot in order to report on how
 * long the boot is taking. So repaints are rate limited - a run of fast steps
 * collapses into one, while a slow step gets its own, which is exactly where
 * the information is wanted.
 */
#include <Arduino.h>
#include <GxEPD2_BW.h>
#include <Fonts/FreeMonoBold9pt7b.h>

#include "boot_screen.h"
#include "utilities.h"
#include "assets/boot_icons.h"

/* main.cpp owns the panel. Declared here rather than moved to a header because
 * the type is a mouthful and nothing else needs it. */
extern GxEPD2_BW<GxEPD2_310_GDEQ031T10, GxEPD2_310_GDEQ031T10::HEIGHT> display;

//************************************[ layout ]********************************
#define BOOT_COLS      4
#define BOOT_ROWS      3
#define BOOT_CELL_W    (LCD_HOR_SIZE / BOOT_COLS)   // 60
#define BOOT_CELL_H    64
#define BOOT_GRID_TOP  46
#define BOOT_BOX       42                           // the frame round each icon

// How long the panel is left alone between repaints. See the note above.
#define BOOT_MIN_REDRAW_MS 250

enum { BOOT_PENDING = 0, BOOT_OK, BOOT_FAILED };

static const struct {
    const uint8_t *icon;
    const char    *label;
} boot_systems[BOOT_SYSTEM_MAX] = {
    { boot_icon_display,  "Display"  },
    { boot_icon_storage,  "Storage"  },
    { boot_icon_touch,    "Touch"    },
    { boot_icon_keyboard, "Keys"     },
    { boot_icon_charger,  "Charger"  },
    { boot_icon_gauge,    "Battery"  },
    { boot_icon_sdcard,   "SD card"  },
    { boot_icon_gps,      "GPS"      },
    { boot_icon_motion,   "Motion"   },
    { boot_icon_light,    "Light"    },
    { boot_icon_modem,    "Modem"    },
    { boot_icon_mesh,     "Mesh"     },
};

static uint8_t  state[BOOT_SYSTEM_MAX] = { 0 };
static char     caption[40] = "";
static bool     running     = false;
static uint32_t last_paint  = 0;

//************************************[ drawing ]*******************************
/* Adafruit_GFX centres nothing for you, so anything centred has to be measured
 * first. */
static void draw_centred(const char *text, int16_t y)
{
    int16_t  bx, by;
    uint16_t bw, bh;

    display.getTextBounds(text, 0, 0, &bx, &by, &bw, &bh);
    display.setCursor((LCD_HOR_SIZE - bw) / 2 - bx, y);
    display.print(text);
}

static void draw_cell(int idx)
{
    int col = idx % BOOT_COLS;
    int row = idx / BOOT_COLS;

    int16_t cx = col * BOOT_CELL_W + BOOT_CELL_W / 2;
    int16_t cy = BOOT_GRID_TOP + row * BOOT_CELL_H;

    int16_t bx = cx - BOOT_BOX / 2;

    display.drawRoundRect(bx, cy, BOOT_BOX, BOOT_BOX, 6, GxEPD_BLACK);

    /* The frame is drawn for every system, the icon only once that system is
     * up - so the screen visibly fills in as the phone starts, and an empty box
     * at the end is a system that never answered. */
    if(state[idx] != BOOT_PENDING) {
        display.drawBitmap(cx - BOOT_ICON_SIZE / 2, cy + (BOOT_BOX - BOOT_ICON_SIZE) / 2,
                           boot_systems[idx].icon, BOOT_ICON_SIZE, BOOT_ICON_SIZE,
                           GxEPD_BLACK);
    }

    // A failure gets struck through, which reads at a glance where a different
    // shade would not - there are only two of those to work with here.
    if(state[idx] == BOOT_FAILED) {
        display.drawLine(bx + 4, cy + 4, bx + BOOT_BOX - 4, cy + BOOT_BOX - 4, GxEPD_BLACK);
        display.drawLine(bx + 4, cy + BOOT_BOX - 4, bx + BOOT_BOX - 4, cy + 4, GxEPD_BLACK);
    }

    // The label sits under the box in the small built-in font: at 60 pixels a
    // cell, the proportional one runs out of room after five characters.
    display.setFont(0);
    display.setTextSize(1);

    int16_t  tbx, tby;
    uint16_t tbw, tbh;
    display.getTextBounds(boot_systems[idx].label, 0, 0, &tbx, &tby, &tbw, &tbh);
    display.setCursor(cx - tbw / 2, cy + BOOT_BOX + 4);
    display.print(boot_systems[idx].label);
}

static void draw_all(void)
{
    display.fillScreen(GxEPD_WHITE);

    display.setTextColor(GxEPD_BLACK);
    display.setFont(&FreeMonoBold9pt7b);
    draw_centred("lilyphone1", 22);

    for(int i = 0; i < BOOT_SYSTEM_MAX; i++) draw_cell(i);

    // What it is waiting on, and how far through it is.
    int done = 0;
    for(int i = 0; i < BOOT_SYSTEM_MAX; i++) {
        if(state[i] != BOOT_PENDING) done++;
    }

    char progress[24];
    snprintf(progress, sizeof(progress), "%d of %d", done, BOOT_SYSTEM_MAX);

    display.setFont(0);
    display.setTextSize(1);
    draw_centred(progress, LCD_VER_SIZE - 40);

    display.setFont(&FreeMonoBold9pt7b);
    if(caption[0]) draw_centred(caption, LCD_VER_SIZE - 18);
}

/* One pass over the panel. `force` is for the paints that have to happen -
 * the first and the last - regardless of how recently one did. */
static void paint(bool force)
{
    if(!running) return;
    if(!force && (millis() - last_paint) < BOOT_MIN_REDRAW_MS) return;

    display.setPartialWindow(0, 0, LCD_HOR_SIZE, LCD_VER_SIZE);
    display.firstPage();
    do {
        draw_all();
    } while(display.nextPage());

    last_paint = millis();
}

//************************************[ public API ]****************************
void boot_screen_begin(void)
{
    memset(state, BOOT_PENDING, sizeof(state));
    caption[0] = '\0';
    running    = true;

    // A full window pass to start with, so the panel is clean underneath: the
    // partial updates that follow leave whatever was there before.
    display.setFullWindow();
    display.firstPage();
    do {
        draw_all();
    } while(display.nextPage());

    last_paint = millis();
}

void boot_screen_busy(int system)
{
    if(system < 0 || system >= BOOT_SYSTEM_MAX) return;

    snprintf(caption, sizeof(caption), "Starting %s", boot_systems[system].label);
    paint(false);
}

bool boot_screen_done(int system, bool ok)
{
    if(system < 0 || system >= BOOT_SYSTEM_MAX) return ok;

    state[system] = ok ? BOOT_OK : BOOT_FAILED;
    if(!ok) Serial.printf("[BOOT] %s did not start\n", boot_systems[system].label);

    return ok;
}

void boot_screen_finish(void)
{
    snprintf(caption, sizeof(caption), "Ready");
    paint(true);

    running = false;
}
