#!/usr/bin/env python3
"""
Draws the home-screen icons that were not inherited from the vendor and writes
them as LVGL image sources in src/assets/.

The vendor's icons are 50x50 LV_IMG_CF_TRUE_COLOR_ALPHA bitmaps, which at
LV_COLOR_DEPTH 1 is two bytes a pixel: a colour byte and an alpha byte. Ours are
the same shape so menu_btn_create() treats them alike. Black ink, binary alpha -
there is nothing to anti-alias towards on a 1-bit panel.

    pip install pillow
    python tools/gen_menu_icons.py

Each icon is drawn at four times the size and averaged down, then thresholded,
so a curve comes out as a curve rather than a staircase.
"""
from PIL import Image, ImageDraw

SIZE  = 50
SCALE = 4
S     = SIZE * SCALE


def canvas():
    img = Image.new("L", (S, S), 0)
    return img, ImageDraw.Draw(img)


def finish(img):
    small = img.resize((SIZE, SIZE), Image.LANCZOS)
    return small.point(lambda p: 255 if p >= 128 else 0)


def draw_calendar():
    img, d = canvas()
    k = SCALE
    # the pad
    d.rounded_rectangle((6 * k, 10 * k, 44 * k, 46 * k), radius=4 * k, outline=255, width=3 * k)
    # the header band, solid
    d.rectangle((6 * k, 10 * k, 44 * k, 19 * k), fill=255)
    # the two rings
    for x in (16, 34):
        d.rounded_rectangle(((x - 2) * k, 5 * k, (x + 2) * k, 15 * k), radius=2 * k, fill=255)
    # the days
    for row in range(3):
        for col in range(4):
            x = 12 + col * 8
            y = 24 + row * 7
            d.rectangle((x * k, y * k, (x + 4) * k, (y + 4) * k), fill=255)
    return finish(img)


def draw_calc():
    img, d = canvas()
    k = SCALE
    # the body
    d.rounded_rectangle((11 * k, 4 * k, 39 * k, 46 * k), radius=4 * k, outline=255, width=3 * k)
    # the display
    d.rectangle((15 * k, 9 * k, 35 * k, 17 * k), fill=255)
    # the keys
    for row in range(4):
        for col in range(3):
            x = 15 + col * 7
            y = 21 + row * 6
            d.rectangle((x * k, y * k, (x + 5) * k, (y + 4) * k), fill=255)
    return finish(img)


def emit(name, img):
    px = img.load()
    out = []
    out.append('#if defined(LV_LVGL_H_INCLUDE_SIMPLE)\n#include "lvgl.h"\n#else\n#include "lvgl.h"\n#endif\n')
    out.append('#ifndef LV_ATTRIBUTE_MEM_ALIGN\n#define LV_ATTRIBUTE_MEM_ALIGN\n#endif\n')
    guard = "LV_ATTRIBUTE_IMG_" + name.upper()
    out.append("#ifndef %s\n#define %s\n#endif\n" % (guard, guard))
    out.append("/* Generated by tools/gen_menu_icons.py - do not edit by hand. */\n")
    out.append("const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST %s uint8_t %s_map[] = {\n" % (guard, name))
    out.append("#if LV_COLOR_DEPTH == 1 || LV_COLOR_DEPTH == 8\n")
    out.append("  /*Pixel format: Blue: 2 bit, Green: 3 bit, Red: 3 bit, Alpha 8 bit */\n")
    for y in range(SIZE):
        row = []
        for x in range(SIZE):
            a = 0xFF if px[x, y] else 0x00
            row.append("0x00, 0x%02X" % a)
        out.append("  " + ", ".join(row) + ",\n")
    out.append("#endif\n};\n\n")
    out.append("const lv_img_dsc_t %s = {\n" % name)
    out.append("  .header.always_zero = 0,\n  .header.w = %d,\n  .header.h = %d,\n" % (SIZE, SIZE))
    out.append("  .data_size = %d * LV_IMG_PX_SIZE_ALPHA_BYTE,\n" % (SIZE * SIZE))
    out.append("  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,\n  .data = %s_map,\n};\n" % name)
    with open("src/assets/%s.c" % name, "w", newline="\n") as f:
        f.write("".join(out))
    print("wrote src/assets/%s.c" % name)


if __name__ == "__main__":
    emit("img_calendar", draw_calendar())
    emit("img_calc", draw_calc())
